In [3]:
import pandas as pd
import gspread
import numpy as np
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from oauth2client.service_account import ServiceAccountCredentials


In [4]:
    scope = ['https://spreadsheets.google.com/feeds']
    credentials = ServiceAccountCredentials.from_json_keyfile_name('DataAcquisition-1344753247c5.json', scope)
    gc = gspread.authorize(credentials)

In [5]:
spreadsheet_key = '1zL_ZghzuLwb8IS1SDKvBeApeYf3YO3Z-tKtM1kWk5bs'
book = gc.open_by_key(spreadsheet_key)
worksheet = book.worksheet("input")
table = worksheet.get_all_values()

In [6]:
##Convert table data into a dataframe
df = pd.DataFrame(table[1:], columns=table[0])
    
##Only keep columns we need
df = df[['x1', 'x2', 'x3']]
    
##Convert number strings to floats and ints
df = df.apply(pd.to_numeric, errors='ignore')
df.head()
inputData = df
print(inputData)

    x1  x2  x3
0    1   2   1
1    1   1   2
2    2   2   1
3    2   2   1
4    1   1   1
5    2   1   2
6    1   2   2
7    2   1   1
8    2   2   2
9    1   1   1
10   2   1   2
11   1   2   1
12   1   1   2
13   2   2   2
14   1   1   1
15   1   1   2
16   2   2   1
17   1   2   2
18   1   1   2
19   2   2   2
20   1   1   1
21   2   1   2
22   1   2   1
23   1   1   1
24   2   2   2
25   1   2   1
26   1   1   1
27   1   2   2
28   2   1   2
29   2   2   1
30   2   2   1
31   2   1   2
32   2   2   2
33   2   1   1
34   2   1   1
35   2   2   2
36   1   1   1
37   1   2   2
38   1   1   1
39   1   1   1
40   2   2   2
41   1   2   1
42   2   1   2
43   1   2   1


In [7]:
n_inputs = 2 # input vector dimension
n_nodes_hidden_layer_1 = 3 # number of nodes in hidden layer 1
n_nodes_hidden_layer_2 = 3 # number of nodes in hidden layer 2
n_nodes_hidden_layer_3 = 3 # number of nodes in hidden layer 3
n_nodes_hidden_layer_4 = 3 # number of nodes in hidden layer 4

n_output_classes = 1 # number of output classes
numOfepochs = 200
inputData = np.array(inputData)
print(inputData)

[[1 2 1]
 [1 1 2]
 [2 2 1]
 [2 2 1]
 [1 1 1]
 [2 1 2]
 [1 2 2]
 [2 1 1]
 [2 2 2]
 [1 1 1]
 [2 1 2]
 [1 2 1]
 [1 1 2]
 [2 2 2]
 [1 1 1]
 [1 1 2]
 [2 2 1]
 [1 2 2]
 [1 1 2]
 [2 2 2]
 [1 1 1]
 [2 1 2]
 [1 2 1]
 [1 1 1]
 [2 2 2]
 [1 2 1]
 [1 1 1]
 [1 2 2]
 [2 1 2]
 [2 2 1]
 [2 2 1]
 [2 1 2]
 [2 2 2]
 [2 1 1]
 [2 1 1]
 [2 2 2]
 [1 1 1]
 [1 2 2]
 [1 1 1]
 [1 1 1]
 [2 2 2]
 [1 2 1]
 [2 1 2]
 [1 2 1]]


In [8]:
def input_evaluation_set(inputData):
    x = inputData[:, 0:2]
    y = inputData[:, 2:3]
    features = x
    labels = y
    return features, labels


# define placeholder for features, labels hypothesis (output)
xt = tf.placeholder('float', shape=[38,2])
y = tf.placeholder('float', shape=[38,1])
h = tf.placeholder('float', shape=[38,1])

AttributeError: module 'tensorflow' has no attribute 'placeholder'

In [11]:
# Define Neural Network Architecture 
def my_neural_network(xt): # creating a neural network
    
    hidden_layer_1 = {'theta1' :tf.Variable(tf.random_normal([n_inputs, n_nodes_hidden_layer_1])),
                      'biases1' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_1]))}
    
    hidden_layer_2 = {'theta2' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_1, n_nodes_hidden_layer_2])),
                      'biases2' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_2]))}
    
    hidden_layer_3 = {'theta3' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_2, n_nodes_hidden_layer_3])),
                      'biases3' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_3]))}
    
    hidden_layer_4 = {'theta4' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_3, n_nodes_hidden_layer_4])),
                      'biases4' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_4]))}
    output_layer = {'theta4' :tf.Variable(tf.random_normal([n_nodes_hidden_layer_4, n_output_classes])),
                    'biases4' :tf.Variable(tf.random_normal([n_output_classes])),}
    
    # thetas are the weights and biases are the threshold
    # repeat mechanics of the hidden layers until hypthosis has gobal minium error
    # feedforward
    z2 = tf.add(tf.matmul(xt, hidden_layer_1['theta1']), hidden_layer_1['biases1'])
    a2 = tf.sigmoid(z2)
    
    z3 = tf.add(tf.matmul(a2, hidden_layer_2['theta2']), hidden_layer_2['biases2'])
    a3 = tf.sigmoid(z2)
    
    z4 = tf.add(tf.matmul(a3, hidden_layer_3['theta3']), hidden_layer_3['biases3'])
    a4 = tf.sigmoid(z2)
    
    z5 = tf.add(tf.matmul(a4, hidden_layer_4['theta4']), hidden_layer_4['biases4'])
    a5 = tf.sigmoid(z2)
    
    z5 = tf.matmul(a5, output_layer['theta4']) + output_layer['biases4']
    h = tf.sigmoid(z5)
    
    return h

In [12]:
h = my_neural_network(xt)
cost = tf.reduce_mean(((y* tf.log(h)) + ((1-y) * tf.log(1.0-h))) * -1)
optimizer = tf.train.GradientDescentOptimizer(.01).minimize(cost)

In [20]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    writer = tf.summary.FileWriter("logs", sess.graph)
    
    for epoch in range(numOfepochs):
        x_,y_ = input_evaluation_set(inputData)
        _, loss = sess.run([optimizer, cost], feed_dict={xt: x_.tolist(), y:y_.tolist()})
        if epoch % 1000 == 0:
            print ('Epoch:', epoch, 'loss=', loss)
            print('hypothesis', sess.run(h, feed_dict={xt: x_.tolist(), y:y_.tolist()}))
            h_final = h > .05
            
            if (loss <.05):
                break

Epoch: 0 loss= 0.80288076
hypothesis [[0.3725611 ]
 [0.47810045]
 [0.50480866]
 [0.50480866]
 [0.47810045]
 [0.5450731 ]
 [0.3725611 ]
 [0.5450731 ]
 [0.50480866]
 [0.47810045]
 [0.5450731 ]
 [0.3725611 ]
 [0.47810045]
 [0.50480866]
 [0.47810045]
 [0.47810045]
 [0.50480866]
 [0.3725611 ]
 [0.47810045]
 [0.50480866]
 [0.47810045]
 [0.5450731 ]
 [0.3725611 ]
 [0.47810045]
 [0.50480866]
 [0.3725611 ]
 [0.47810045]
 [0.3725611 ]
 [0.5450731 ]
 [0.50480866]
 [0.50480866]
 [0.5450731 ]
 [0.50480866]
 [0.5450731 ]
 [0.5450731 ]
 [0.50480866]
 [0.47810045]
 [0.3725611 ]]
